name: 'CI Setup'
description: 'Install BuckOS build dependencies, QEMU, and configure KVM access'

runs:
  using: 'composite'
  steps:
    - name: Harden apt against flaky mirrors
      shell: bash
      run: |
        echo 'Acquire::ForceIPv4 "true";'       | sudo tee /etc/apt/apt.conf.d/99force-ipv4 >/dev/null
        echo 'Acquire::Queue-Mode "access";'     | sudo tee /etc/apt/apt.conf.d/99queue-mode >/dev/null
        echo 'Acquire::http::Pipeline-Depth "0";' | sudo tee /etc/apt/apt.conf.d/99pipeline >/dev/null
        echo 'Acquire::Retries "3";'             | sudo tee /etc/apt/apt.conf.d/99retries >/dev/null
        echo 'Acquire::Languages "none";'        | sudo tee /etc/apt/apt.conf.d/99no-languages >/dev/null
        echo 'Dpkg::Use-Pty "0";'               | sudo tee /etc/apt/apt.conf.d/99no-pty >/dev/null
        sudo sed -i -E \
          -e 's|https?://([a-z0-9-]+\.)*archive\.ubuntu\.com/ubuntu|mirror://mirrors.ubuntu.com/mirrors.txt|g' \
          -e 's|https?://security\.ubuntu\.com/ubuntu|mirror://mirrors.ubuntu.com/mirrors.txt|g' \
          /etc/apt/sources.list /etc/apt/sources.list.d/*.list 2>/dev/null || true
        sudo rm -f /etc/apt/sources.list.d/*.list

    - name: Install dependencies
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        bash setup.sh --yes
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

    - name: Install QEMU
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        case "$(dpkg --print-architecture)" in
          amd64) sudo apt-get install -y --no-install-recommends qemu-system-x86 ;;
          arm64) sudo apt-get install -y --no-install-recommends qemu-system-arm ;;
        esac

    - name: Configure KVM access
      shell: bash
      run: |
        if [ -e /dev/kvm ] && [ ! -f /etc/udev/rules.d/99-kvm4all.rules ]; then
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' \
            | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
        elif [ ! -e /dev/kvm ]; then
          echo "::warning::/dev/kvm not found — integration tests will fail"
        fi
