# BXL graph structure tests.
#
# Run with:
#   buck2 bxl //tests/graph:test_deps.bxl
#   buck2 bxl //tests/graph:test_use_flags.bxl
#   buck2 bxl //tests/graph:test_transforms.bxl
#   buck2 bxl //tests/graph:test_labels.bxl
#   buck2 bxl //tests/graph:test_labels.bxl:test_label_coverage
#   buck2 bxl //tests/graph:test_versions.bxl
#   buck2 bxl //tests/graph:test_targets.bxl
#   buck2 bxl //tests/graph:test_provenance.bxl
#   buck2 bxl //tests/graph:test_graph.bxl

export_file(
    name = "test_deps.bxl",
    src = "test_deps.bxl",
    visibility = ["PUBLIC"],
)

export_file(
    name = "test_use_flags.bxl",
    src = "test_use_flags.bxl",
    visibility = ["PUBLIC"],
)

export_file(
    name = "test_transforms.bxl",
    src = "test_transforms.bxl",
    visibility = ["PUBLIC"],
)

export_file(
    name = "test_labels.bxl",
    src = "test_labels.bxl",
    visibility = ["PUBLIC"],
)

export_file(
    name = "test_versions.bxl",
    src = "test_versions.bxl",
    visibility = ["PUBLIC"],
)

export_file(
    name = "test_targets.bxl",
    src = "test_targets.bxl",
    visibility = ["PUBLIC"],
)

export_file(
    name = "test_provenance.bxl",
    src = "test_provenance.bxl",
    visibility = ["PUBLIC"],
)

export_file(
    name = "test_graph.bxl",
    src = "test_graph.bxl",
    visibility = ["PUBLIC"],
)

export_file(
    name = "test_cloud_hypervisor.bxl",
    src = "test_cloud_hypervisor.bxl",
    visibility = ["PUBLIC"],
)
