#!/usr/bin/env python3
"""Generate a QEMU boot script.

Replaces the inline bash in boot.bzl _qemu_boot_script_impl.  Pure file
generation — no subprocess calls needed.
"""

import argparse
import os
import stat
import sys

from _env import sanitize_global_env

_SCRIPT_TEMPLATE = """\
#!/bin/bash
# QEMU Boot Script for BuckOs
# Generated by Buck2 build system

set -e
unset CDPATH

# Find project root by locating buck-out directory
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR"
while [ "$PROJECT_ROOT" != "/" ]; do
    if [ -d "$PROJECT_ROOT/buck-out" ] && [ -f "$PROJECT_ROOT/.buckroot" -o -f "$PROJECT_ROOT/.buckconfig" ]; then
        break
    fi
    PROJECT_ROOT="$(dirname "$PROJECT_ROOT")"
done

if [ "$PROJECT_ROOT" = "/" ]; then
    PROJECT_ROOT="$SCRIPT_DIR"
    while [[ "$PROJECT_ROOT" == *"/buck-out/"* ]]; do
        PROJECT_ROOT="$(dirname "$PROJECT_ROOT")"
    done
    PROJECT_ROOT="$(dirname "$PROJECT_ROOT")"
fi

cd "$PROJECT_ROOT"

KERNEL="{kernel}"
INITRAMFS="{initramfs}"

echo "Booting BuckOs with QEMU..."
echo "  Kernel: $KERNEL"
echo "  Initramfs: $INITRAMFS"
echo ""
echo "Press Ctrl-A X to exit QEMU"
echo ""

{qemu_bin} \\
    -machine {machine} \\
    -m {memory} \\
    -smp {cpus} \\
    -kernel "$KERNEL" \\
    -initrd "$INITRAMFS" \\
    -append "{kernel_args}" \\
    -nographic \\
    -no-reboot \\
    {extra_args} \\
    "$@"
"""


def main():
    parser = argparse.ArgumentParser(description="Generate QEMU boot script")
    parser.add_argument("--kernel", required=True)
    parser.add_argument("--initramfs", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--qemu-bin", default="qemu-system-x86_64")
    parser.add_argument("--machine", default="q35")
    parser.add_argument("--memory", default="512M")
    parser.add_argument("--cpus", default="2")
    parser.add_argument("--kernel-args", default="console=ttyS0 quiet")
    parser.add_argument("--extra-args", default="")
    args = parser.parse_args()

    sanitize_global_env()

    script = _SCRIPT_TEMPLATE.format(
        kernel=args.kernel,
        initramfs=args.initramfs,
        qemu_bin=args.qemu_bin,
        machine=args.machine,
        memory=args.memory,
        cpus=args.cpus,
        kernel_args=args.kernel_args,
        extra_args=args.extra_args,
    )

    output = os.path.abspath(args.output)
    os.makedirs(os.path.dirname(output) or ".", exist_ok=True)
    with open(output, "w") as f:
        f.write(script)
    os.chmod(output, os.stat(output).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


if __name__ == "__main__":
    main()
