python_binary(
    name = "extract",
    main = "extract.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "patch_helper",
    main = "patch_helper.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "configure_helper",
    main = "configure_helper.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "cmake_helper",
    main = "cmake_helper.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "meson_helper",
    main = "meson_helper.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "build_helper",
    main = "build_helper.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "install_helper",
    main = "install_helper.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "strip_helper",
    main = "strip_helper.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "stamp_helper",
    main = "stamp_helper.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "ima_helper",
    main = "ima_helper.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "cargo_helper",
    main = "cargo_helper.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "go_helper",
    main = "go_helper.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "python_helper",
    main = "python_helper.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "mozbuild_helper",
    main = "mozbuild_helper.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "merge_host_tools",
    main = "merge_host_tools.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "toolchain_pack",
    main = "toolchain_pack.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "toolchain_unpack",
    main = "toolchain_unpack.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "vm_test_runner",
    main = "vm_test_runner.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "kernel_config",
    main = "kernel_config.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "kernel_headers",
    main = "kernel_headers.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "kernel_build",
    main = "kernel_build.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "kernel_btf_headers",
    main = "kernel_btf_headers.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "kernel_modules_install",
    main = "kernel_modules_install.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "iso_helper",
    main = "iso_helper.py",
    visibility = ["PUBLIC"],
)

export_file(
    name = "sbom.bxl",
    src = "sbom.bxl",
    visibility = ["PUBLIC"],
)
